project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: false
  resources:
    - "datasets/*.sql"
    - "datasets/schema/*.png"

website:
  site-url: "https://seek.onlinedegree.iitm.ac.in/courses/ns_26t2_cs1902"
  description: "Course materials for CS2001 Database Management Systems"
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Welcome!** Scroll to the bottom of any chapter to ask questions, review, and get answers!"
    type: secondary
  reader-mode: true

comments:
  giscus:
    repo: cs2001-dbms/cs2001-dbms.github.io
    category: General
    mapping: pathname
    input-position: top
    reactions-enabled: true
    loading: lazy

book:
  title: "Database Management Systems"
  page-navigation: true
  date-format: long
  repo-url: https://github.com/cs2001-dbms/cs2001-dbms.github.io
  repo-actions: [edit, issue]
  page-footer: 
    center: "© CS2001 - Database Management Systems"
  search:
    location: sidebar
    type: textbox
    keyboard-shortcut: f
    copy-button: true
  sidebar:
    title: "DBMS [CS2001]"
    logo: cover.png
    search: true
    collapse-level: 1
    style: floating
    sticky-header: true  # Makes the sidebar header sticky as the user scrolls.
    transition: 0.3s ease  # Smooth transition for sidebar animations
    tools:
      - icon: chat-text
        href: "javascript:window.scrollTo(0, document.body.scrollHeight);"
        text: "Ask Questions & Review"
      - icon: play-circle
        href: "https://www.youtube.com/@dbms-iitmadrasbsdegree1439/streams"
        text: "Lecture Streams"
      - icon: people
        href: "https://discourse.onlinedegree.iitm.ac.in/c/courses/dbms-kb"
        text: "Discourse Community"
      - icon: envelope
        href: "mailto:pravins@study.iitm.ac.in,manidipa@study.iitm.ac.in"
        text: "Contact Instructors"
      - icon: folder
        href: "https://drive.google.com/drive/folders/1TglQNLuExuxpkPg7KdHFlZaX4jIvkECY"
        text: "Live Session Slides"
  chapters:
    - href: index.qmd
      text: "About the Course"
    - part: '**Week-01**'
      chapters: 
        - weeks/week_1/intro_to_dbms.qmd
        - weeks/week_1/view_of_data.qmd
        - weeks/week_1/database_design.qmd
    - part: '**Week-02**'
      chapters: 
        - weeks/week_2/01_relational_and_ddl.qmd
        - weeks/week_2/02_dml_and_queries.qmd
        - weeks/week_2/03_advanced_sql.qmd
    - part: '**Week-03**'
      chapters:
        - weeks/week_3/nested_subqueries.qmd
        - weeks/week_3/joins.qmd
        - weeks/week_3/intermediate_sql.qmd
        - weeks/week_3/advanced_sql.qmd
    - part: '**Week-04**'
      chapters:
        - weeks/week_4/01_relational_algebra_and_calculus.qmd
        - weeks/week_4/02_entity_relationship_model.qmd
        - weeks/week_4/03_advanced_er_concepts.qmd
    - part: '**Week-05**'
      chapters:
        - weeks/week_5/01.qmd
        - weeks/week_5/02.qmd
        - weeks/week_5/03.qmd
        - weeks/week_5/04.qmd
    - part: '**Playground**'
      chapters: 
        - sql_playground.qmd
        - pythonDB_playground.qmd
  favicon: logo.ico

format:
  html:
    grid:
      sidebar-width: 240px
      body-width: 1020px
      margin-width: 200px
      gutter-width: 1.2rem
    theme:
      light: flatly
      dark: darkly  
    css: style.css
    lightbox: true
    animations:
      hover: true  # Enable smooth hover transitions
      fade-in: true # Add fade-in effects for content
    toc: true # table of contents 
    toc-location: right  
    toc-collapsible: true
    toc-title: "**On this page**"
    toc-indent: 2em
    toc-depth: 2
    toc-expand: true
    number-sections: false  # Disable numbering globally
    code:
      highlight: pygments
      theme:
        light: github
        dark: monokai
    code-fold: true
    code-copy: true
    code-line-numbers: true
    code-link: true
    code-overflow: wrap

    format-links: true
    reader-mode: true
    reading-progress: true
    code-annotations: hover
    anchor-sections: true
    citations-hover: true
    footnotes-hover: true
    reading-time: true
    link-external-icon: true
    link-external-newwindow: true
    math: katex
    smooth-scroll: true
    scroll-to-top-button: true
    lazy-load: true # Enable lazy loading
    image-lazy-loading: true # Enable lazy loading for images
    optimize-images: true  # Automatically optimize images
    optimize-assets: true  # Optimize assets like JS and CSS for faster load
  pdf:
    pdf-engine: xelatex
    papersize: letter
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    highlight-style: pygments
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
